#!/usr/bin/env ruby
# frozen_string_literal: true

require 'linode/ip'

$stdout.sync = true
$stderr.sync = true

name = ARGV[0] || ENV['LINODES_LIST_NAME']
puts Class.extend(Linode::Ip).fetch(name) if name
